language: node_js

sudo: required

services:
  - docker

node_js:
  - stable

script:
  - npm run test && npm run integration

after_script:
  - npm run coveralls

cache:
  directories:
    - node_modules
